// lib/intelligence/searchTaxonomy.js
// ForgeTomorrow Search Taxonomy
// Central source of truth for search aliases, capability clusters,
// intent families, semantic expansions, and conflicting ecosystems.

export const TERM_ALIASES = {
  customer: [
    'customer support',
    'customer success',
    'customer service',
    'customer experience',
    'client services',
    'client success',
    'account management',
  ],

  'customer support': [
    'customer service',
    'technical support',
    'support representative',
    'support specialist',
    'client support',
    'client services',
    'help desk',
    'service desk',
    'customer operations',
  ],

  'customer success': [
    'client success',
    'customer experience',
    'account management',
    'customer onboarding',
    'renewals',
    'retention',
    'relationship management',
  ],

  'customer service': [
    'customer support',
    'support representative',
    'service representative',
    'client services',
    'customer care',
    'customer operations',
  ],

  'customer service manager': [
    'customer service',
    'customer support',
    'support manager',
    'customer operations',
    'client services manager',
    'service delivery manager',
    'customer success',
    'client success',
    'escalation management',
    'support delivery',
  ],

  'customer support manager': [
    'customer support',
    'support manager',
    'technical support manager',
    'client services manager',
    'service delivery manager',
    'customer success',
    'client success',
    'customer operations',
    'support delivery',
  ],

  'customer success manager': [
    'customer success',
    'client success',
    'account management',
    'customer onboarding',
    'renewals',
    'retention',
    'customer engagement',
  ],

  'desktop technician': [
    'desktop support',
    'desktop tech',
    'deskside support',
    'deskside services',
    'it support',
    'technical support',
    'help desk',
    'service desk',
    'endpoint support',
    'euc support',
    'end user support',
    'workplace support',
  ],

  'desktop support': [
    'desktop technician',
    'desktop tech',
    'deskside support',
    'deskside services',
    'it support',
    'technical support',
    'help desk',
    'service desk',
    'endpoint support',
    'euc support',
    'end user support',
    'workplace support',
  ],

  'deskside support': [
    'desktop support',
    'desktop technician',
    'desktop tech',
    'deskside services',
    'it support',
    'technical support',
    'endpoint support',
    'euc support',
    'end user support',
    'workplace support',
  ],

  'endpoint support': [
    'desktop support',
    'desktop technician',
    'desktop tech',
    'deskside support',
    'deskside services',
    'it support',
    'technical support',
    'euc support',
    'end user support',
    'workplace support',
  ],

  'euc support': [
    'desktop support',
    'desktop technician',
    'desktop tech',
    'deskside support',
    'deskside services',
    'endpoint support',
    'end user support',
    'workplace support',
  ],

  'software engineer': [
    'software developer',
    'full stack developer',
    'backend developer',
    'frontend developer',
    'web developer',
  ],

  'project manager': [
    'program manager',
    'delivery manager',
    'technical project manager',
    'implementation manager',
    'project coordinator',
    'scrum master',
  ],

  operations: [
    'business operations',
    'operations manager',
    'operations coordinator',
    'process improvement',
    'workflow optimization',
  ],

  sales: [
    'account executive',
    'sales representative',
    'business development',
    'sales development',
    'sdr',
    'bdr',
  ],

  marketing: [
    'growth marketing',
    'digital marketing',
    'content marketing',
    'brand marketing',
    'campaign management',
  ],

  hr: [
    'human resources',
    'people operations',
    'employee relations',
    'hr generalist',
    'hr business partner',
  ],

  recruiter: [
    'talent acquisition',
    'recruiting',
    'sourcer',
    'technical recruiter',
    'recruitment coordinator',
  ],

  finance: [
    'accounting',
    'financial analyst',
    'accounts payable',
    'accounts receivable',
    'bookkeeping',
  ],

  healthcare: [
    'medical assistant',
    'patient care',
    'clinical',
    'healthcare administration',
    'medical office',
  ],

  education: [
    'teacher',
    'instructor',
    'trainer',
    'curriculum',
    'learning and development',
  ],

  legal: [
    'paralegal',
    'legal assistant',
    'contracts',
    'compliance',
    'regulatory',
  ],

  logistics: [
    'supply chain',
    'warehouse',
    'shipping',
    'receiving',
    'inventory',
    'procurement',
  ],

  manufacturing: [
    'production',
    'quality control',
    'assembly',
    'machine operator',
    'plant operations',
  ],

  data: [
    'data analyst',
    'business intelligence',
    'reporting analyst',
    'analytics',
    'power bi',
  ],
};

export const CAPABILITY_CLUSTERS = {
  customerSupport: [
    'zendesk',
    'retention',
    'onboarding',
    'customer support',
    'customer service',
    'customer care',
    'support representative',
    'support specialist',
    'technical support',
    'ticketing',
    'sla',
    'client support',
    'client services',
    'service delivery',
    'escalation management',
    'support delivery',
    'incident management',
    'itil',
    'knowledge management',
    'servicenow',
    'salesforce',
    'team leadership',
  ],

  customerSuccess: [
    'customer success',
    'client success',
    'customer experience',
    'account management',
    'customer onboarding',
    'relationship management',
    'renewals',
    'retention',
    'customer engagement',
    'saas',
    'qbr',
    'stakeholder management',
    'csat',
    'upsell',
    'cross-functional',
  ],

  desktopSupport: [
    'active directory',
    'sccm',
    'intune',
    'jamf',
    'okta',
    'office 365',
    'microsoft 365',
    'vpn',
    'windows',
    'endpoint',
    'servicenow',
    'help desk',
    'service desk',
    'desktop support',
    'desktop technician',
    'desktop tech',
    'deskside support',
    'deskside services',
    'endpoint support',
    'euc support',
    'end user support',
    'workplace support',
    'technical support',
  ],

  softwareEngineering: [
    'javascript',
    'typescript',
    'react',
    'next.js',
    'node.js',
    'python',
    'java',
    'c#',
    '.net',
    'sql',
    'api',
    'full stack',
    'frontend',
    'backend',
    'software architecture',
    'microservices',
    'git',
  ],

  cloudInfrastructure: [
    'aws',
    'azure',
    'gcp',
    'terraform',
    'kubernetes',
    'docker',
    'linux',
    'windows server',
    'virtualization',
    'vmware',
    'cloud infrastructure',
    'devops',
    'ci/cd',
    'infrastructure as code',
  ],

  executiveLeadership: [
    'founder',
    'chief executive officer',
    'ceo',
    'company strategy',
    'product strategy',
    'business model',
    'go-to-market',
    'fundraising',
    'investor',
    'ip strategy',
    'platform architecture',
    'organizational scaling',
    'p&l',
    'partnerships',
    'roadmap',
    'market positioning',
  ],


  cybersecurity: [
    'siem',
    'splunk',
    'sentinel',
    'crowdstrike',
    'defender',
    'edr',
    'soc',
    'incident response',
    'threat hunting',
    'vulnerability management',
    'firewall',
    'iam',
    'okta',
    'mfa',
    'zero trust',
    'phishing',
    'security operations',
  ],

  networking: [
    'cisco',
    'meraki',
    'fortinet',
    'palo alto',
    'vpn',
    'tcp/ip',
  ],

  sales: [
    'sales',
    'account executive',
    'business development',
    'sales development',
    'sdr',
    'bdr',
    'prospecting',
    'lead generation',
    'pipeline',
    'quota',
    'crm',
    'salesforce',
    'hubspot',
    'negotiation',
    'closing',
  ],

  marketing: [
    'marketing',
    'growth marketing',
    'digital marketing',
    'content marketing',
    'campaign management',
    'brand strategy',
    'seo',
    'sem',
    'paid media',
    'email marketing',
    'google analytics',
    'social media',
    'demand generation',
    'marketing automation',
  ],

  operations: [
    'operations',
    'business operations',
    'process improvement',
    'workflow optimization',
    'kpi',
    'sop',
    'vendor management',
    'resource planning',
    'quality assurance',
    'continuous improvement',
    'lean',
    'six sigma',
    'reporting',
  ],

  projectManagement: [
    'project management',
    'program management',
    'delivery management',
    'implementation',
    'scrum',
    'agile',
    'jira',
    'roadmap',
    'stakeholder management',
    'risk management',
    'timeline',
    'milestones',
    'budget',
  ],

  humanResources: [
    'human resources',
    'hr',
    'people operations',
    'employee relations',
    'benefits',
    'compensation',
    'hris',
    'workday',
    'adp',
    'policy',
    'performance management',
    'onboarding',
    'employee engagement',
  ],

  recruiting: [
    'recruiting',
    'talent acquisition',
    'sourcing',
    'candidate screening',
    'interview coordination',
    'applicant tracking',
    'ats',
    'technical recruiter',
    'recruiter',
    'talent pipeline',
    'job posting',
    'offer coordination',
  ],

  financeAccounting: [
    'finance',
    'accounting',
    'bookkeeping',
    'financial analysis',
    'budgeting',
    'forecasting',
    'accounts payable',
    'accounts receivable',
    'payroll',
    'reconciliation',
    'general ledger',
    'audit',
    'quickbooks',
    'excel',
  ],

  healthcareAdmin: [
    'healthcare',
    'medical office',
    'patient scheduling',
    'patient care',
    'clinical support',
    'medical records',
    'emr',
    'ehr',
    'hipaa',
    'insurance verification',
    'billing',
    'claims',
    'front desk',
  ],

  educationTraining: [
    'education',
    'teaching',
    'training',
    'instruction',
    'curriculum',
    'lesson planning',
    'learning and development',
    'facilitation',
    'classroom management',
    'coaching',
    'e-learning',
    'instructional design',
  ],

  legalCompliance: [
    'legal',
    'paralegal',
    'legal assistant',
    'contracts',
    'compliance',
    'regulatory',
    'risk management',
    'policy review',
    'case management',
    'document review',
    'legal research',
    'privacy',
  ],

  logisticsSupplyChain: [
    'logistics',
    'supply chain',
    'warehouse',
    'inventory',
    'shipping',
    'receiving',
    'procurement',
    'purchasing',
    'vendor coordination',
    'freight',
    'distribution',
    'materials management',
  ],

  manufacturing: [
    'manufacturing',
    'production',
    'assembly',
    'machine operator',
    'quality control',
    'quality assurance',
    'plant operations',
    'safety',
    'maintenance',
    'lean manufacturing',
    'inspection',
    'materials',
  ],

  dataAnalytics: [
    'data analyst',
    'analytics',
    'business intelligence',
    'reporting',
    'dashboard',
    'sql',
    'excel',
    'power bi',
    'tableau',
    'data visualization',
    'kpi',
    'metrics',
    'forecasting',
  ],
};

export const JOB_INTENT_FAMILIES = {
  customer: {
    primaryClusters: ['customerSupport', 'customerSuccess'],
    semanticTerms: [
      'customer support',
      'customer success',
      'customer service',
      'customer experience',
      'client services',
      'client success',
      'account management',
    ],
  },

  customerSupport: {
    triggers: [
      'customer support',
      'customer service',
      'support manager',
      'technical support',
      'help desk',
      'service desk',
      'client services',
      'customer care',
    ],
    primaryClusters: ['customerSupport'],
    adjacentClusters: ['customerSuccess', 'desktopSupport'],
    semanticTerms: [
      'customer support',
      'customer service',
      'technical support',
      'client services',
      'support representative',
      'support specialist',
      'customer operations',
      'help desk',
      'service desk',
    ],
  },

  customerSuccess: {
    triggers: [
      'customer success',
      'client success',
      'account manager',
      'account management',
      'customer experience',
      'customer onboarding',
      'renewals',
      'retention',
    ],
    primaryClusters: ['customerSuccess'],
    adjacentClusters: ['customerSupport'],
    semanticTerms: [
      'customer success',
      'client success',
      'customer experience',
      'account management',
      'customer onboarding',
      'relationship management',
      'renewals',
      'retention',
    ],
  },


  desktopSupport: {
    triggers: [
      'desktop support',
      'desktop technician',
      'desktop tech',
      'deskside support',
      'deskside services',
      'endpoint support',
      'euc support',
      'end user support',
      'workplace support',
      'it support',
      'technical support',
      'help desk',
      'service desk',
    ],
    primaryClusters: ['desktopSupport'],
    adjacentClusters: ['customerSupport', 'networking'],
    semanticTerms: [
      'desktop support',
      'desktop technician',
      'desktop tech',
      'deskside support',
      'deskside services',
      'endpoint support',
      'euc support',
      'end user support',
      'workplace support',
      'it support',
      'technical support',
      'help desk',
      'service desk',
    ],
  },

  softwareEngineering: {
    triggers: [
      'frontend',
      'developer',
      'software',
      'engineer',
      'full stack',
      'backend',
      'react',
      'next.js',
      'typescript',
    ],
    primaryClusters: ['softwareEngineering'],
    adjacentClusters: ['cloudInfrastructure', 'dataAnalytics'],
    semanticTerms: [
      'software engineer',
      'software developer',
      'full stack developer',
      'frontend developer',
      'backend developer',
      'web developer',
    ],
  },

  cloudInfrastructure: {
    triggers: [
      'cloud',
      'devops',
      'infrastructure',
      'aws',
      'azure',
      'gcp',
      'kubernetes',
      'terraform',
    ],
    primaryClusters: ['cloudInfrastructure'],
    adjacentClusters: ['softwareEngineering', 'cybersecurity'],
    semanticTerms: [
      'cloud engineer',
      'devops engineer',
      'infrastructure engineer',
      'cloud infrastructure',
      'systems engineer',
    ],
  },

  cybersecurity: {
    triggers: [
      'cybersecurity',
      'security analyst',
      'soc analyst',
      'incident response',
      'threat hunting',
      'security engineer',
    ],
    primaryClusters: ['cybersecurity'],
    adjacentClusters: ['networking', 'cloudInfrastructure'],
    semanticTerms: [
      'cybersecurity',
      'security analyst',
      'soc analyst',
      'incident response',
      'threat hunting',
      'security operations',
    ],
  },

  sales: {
    triggers: [
      'sales',
      'account executive',
      'business development',
      'sales development',
      'sdr',
      'bdr',
      'revenue',
    ],
    primaryClusters: ['sales'],
    adjacentClusters: ['marketing', 'customerSuccess'],
    semanticTerms: [
      'sales',
      'account executive',
      'business development',
      'sales development',
      'lead generation',
      'pipeline',
      'crm',
    ],
  },

  marketing: {
    triggers: [
      'marketing',
      'growth',
      'demand generation',
      'content marketing',
      'digital marketing',
      'brand',
      'seo',
      'social media',
    ],
    primaryClusters: ['marketing'],
    adjacentClusters: ['sales', 'dataAnalytics'],
    semanticTerms: [
      'marketing',
      'growth marketing',
      'digital marketing',
      'campaign management',
      'brand strategy',
      'content marketing',
      'demand generation',
    ],
  },

  operations: {
    triggers: [
      'operations',
      'business operations',
      'operations manager',
      'process improvement',
      'workflow',
      'quality assurance',
    ],
    primaryClusters: ['operations'],
    adjacentClusters: ['projectManagement', 'dataAnalytics'],
    semanticTerms: [
      'operations',
      'business operations',
      'process improvement',
      'workflow optimization',
      'quality assurance',
      'kpi',
    ],
  },

  projectManagement: {
    triggers: [
      'project manager',
      'program manager',
      'delivery manager',
      'implementation manager',
      'scrum master',
      'agile',
    ],
    primaryClusters: ['projectManagement'],
    adjacentClusters: ['operations'],
    semanticTerms: [
      'project management',
      'program management',
      'delivery management',
      'implementation',
      'scrum',
      'agile',
      'stakeholder management',
    ],
  },

  humanResources: {
    triggers: [
      'human resources',
      'hr',
      'people operations',
      'employee relations',
      'hr generalist',
      'hr business partner',
    ],
    primaryClusters: ['humanResources'],
    adjacentClusters: ['recruiting'],
    semanticTerms: [
      'human resources',
      'people operations',
      'employee relations',
      'hris',
      'benefits',
      'compensation',
    ],
  },

  recruiting: {
    triggers: [
      'recruiter',
      'recruiting',
      'talent acquisition',
      'sourcer',
      'recruitment',
      'candidate screening',
    ],
    primaryClusters: ['recruiting'],
    adjacentClusters: ['humanResources', 'sales'],
    semanticTerms: [
      'recruiting',
      'talent acquisition',
      'sourcing',
      'candidate screening',
      'interview coordination',
      'ats',
    ],
  },

  financeAccounting: {
    triggers: [
      'finance',
      'accounting',
      'financial analyst',
      'bookkeeper',
      'payroll',
      'accounts payable',
      'accounts receivable',
    ],
    primaryClusters: ['financeAccounting'],
    adjacentClusters: ['dataAnalytics'],
    semanticTerms: [
      'finance',
      'accounting',
      'financial analysis',
      'budgeting',
      'forecasting',
      'payroll',
      'reconciliation',
    ],
  },

  healthcareAdmin: {
    triggers: [
      'healthcare',
      'medical assistant',
      'medical office',
      'patient care',
      'clinical',
      'medical records',
      'billing',
      'claims',
    ],
    primaryClusters: ['healthcareAdmin'],
    adjacentClusters: ['customerSupport'],
    semanticTerms: [
      'healthcare',
      'medical office',
      'patient scheduling',
      'patient care',
      'clinical support',
      'medical records',
      'hipaa',
    ],
  },

  educationTraining: {
    triggers: [
      'teacher',
      'education',
      'training',
      'instructor',
      'trainer',
      'curriculum',
      'learning and development',
    ],
    primaryClusters: ['educationTraining'],
    adjacentClusters: ['humanResources'],
    semanticTerms: [
      'education',
      'training',
      'instruction',
      'curriculum',
      'learning and development',
      'facilitation',
      'coaching',
    ],
  },

  legalCompliance: {
    triggers: [
      'legal',
      'paralegal',
      'legal assistant',
      'compliance',
      'contracts',
      'regulatory',
      'risk',
    ],
    primaryClusters: ['legalCompliance'],
    adjacentClusters: ['operations'],
    semanticTerms: [
      'legal',
      'paralegal',
      'contracts',
      'compliance',
      'regulatory',
      'risk management',
      'document review',
    ],
  },

  logisticsSupplyChain: {
    triggers: [
      'logistics',
      'supply chain',
      'warehouse',
      'inventory',
      'shipping',
      'receiving',
      'procurement',
    ],
    primaryClusters: ['logisticsSupplyChain'],
    adjacentClusters: ['operations', 'manufacturing'],
    semanticTerms: [
      'logistics',
      'supply chain',
      'warehouse',
      'inventory',
      'shipping',
      'receiving',
      'procurement',
    ],
  },

  manufacturing: {
    triggers: [
      'manufacturing',
      'production',
      'assembly',
      'machine operator',
      'quality control',
      'plant operations',
    ],
    primaryClusters: ['manufacturing'],
    adjacentClusters: ['logisticsSupplyChain', 'operations'],
    semanticTerms: [
      'manufacturing',
      'production',
      'assembly',
      'machine operator',
      'quality control',
      'plant operations',
    ],
  },

  dataAnalytics: {
    triggers: [
      'data analyst',
      'analytics',
      'business intelligence',
      'reporting analyst',
      'dashboard',
      'power bi',
      'tableau',
    ],
    primaryClusters: ['dataAnalytics'],
    adjacentClusters: ['operations', 'financeAccounting', 'marketing'],
    semanticTerms: [
      'data analyst',
      'analytics',
      'business intelligence',
      'reporting',
      'dashboard',
      'sql',
      'power bi',
      'tableau',
    ],
  },
};

export const CONFLICTING_ECOSYSTEMS = {
  customerSupport: [
    'react',
    'next.js',
    'typescript',
    'frontend',
    'backend',
    'full stack',
    'postgresql',
    'supabase',
    'openai api',
    'llm',
    'ai sdk',
    'sales development',
    'b2b sales',
    'load management',
    'demand response',
    'energy management',
  ],

  customerSuccess: [
    'react',
    'next.js',
    'typescript',
    'frontend',
    'backend',
    'full stack',
    'postgresql',
    'supabase',
    'openai api',
    'llm',
    'ai sdk',
    'sales development',
    'b2b sales',
    'load management',
    'demand response',
    'energy management',
  ],

  softwareEngineering: [
    'call center',
    'customer service representative',
    'customer support representative',
    'support agent',
    'patient care',
    'warehouse',
    'forklift',
    'assembly',
  ],

  sales: [
    'patient care',
    'warehouse',
    'machine operator',
    'clinical',
  ],

  marketing: [
    'forklift',
    'warehouse',
    'patient care',
    'machine operator',
  ],

  healthcareAdmin: [
    'react',
    'next.js',
    'software engineer',
    'warehouse',
    'forklift',
  ],

  manufacturing: [
    'react',
    'next.js',
    'customer success',
    'legal assistant',
  ],

  logisticsSupplyChain: [
    'react',
    'next.js',
    'software engineer',
    'customer success manager',
  ],
};

export function getJobSearchIntent(keyword = '') {
  const q = String(keyword || '').trim().toLowerCase();

  if (!q) {
    return {
      intentKey: '',
      primaryClusters: [],
      adjacentClusters: [],
      semanticTerms: [],
    };
  }

  if (q === 'customer') {
    return {
      intentKey: 'customer',
      primaryClusters: JOB_INTENT_FAMILIES.customer.primaryClusters,
      adjacentClusters: [],
      semanticTerms: JOB_INTENT_FAMILIES.customer.semanticTerms,
    };
  }

  for (const [intentKey, config] of Object.entries(JOB_INTENT_FAMILIES)) {
    if (intentKey === 'customer') continue;

    const triggers = Array.isArray(config.triggers) ? config.triggers : [];

    if (triggers.some((term) => q.includes(term))) {
      return {
        intentKey,
        primaryClusters: config.primaryClusters || [],
        adjacentClusters: config.adjacentClusters || [],
        semanticTerms: config.semanticTerms || [],
      };
    }
  }

  return {
    intentKey: '',
    primaryClusters: [],
    adjacentClusters: [],
    semanticTerms: [q],
  };
}
