export const profileWallpapers = [
  { key: "building_teams", name: "Building Teams", desc: "People standing together", src: "/profile-wallpaper/Building_Teams.jpg" },
  { key: "forge", name: "Forge", desc: "Smoke and lava", src: "/profile-wallpaper/Forge.jpg" },
  { key: "future", name: "Future", desc: "AI shaking human hand", src: "/profile-wallpaper/Future.jpg" },
  { key: "growth", name: "Growth", desc: "Green forest", src: "/profile-wallpaper/Growth.jpg" },
  { key: "journey", name: "Journey", desc: "Road and green fields", src: "/profile-wallpaper/Journey.jpg" },
  { key: "leadership", name: "Leadership", desc: "Sunrise in mountains", src: "/profile-wallpaper/Leadership.jpg" },
  { key: "network", name: "Network", desc: "Blue stars connecting", src: "/profile-wallpaper/Network.jpg" },
  
  { key: "creation", name: "Creation", desc: "Canvas with paint pallet and brushes", src: "/profile-wallpapers/Creation.jpg",
  },
  {
    key: "courage",
    name: "Courage",
    desc: "Fire service dedication",
    category: "Public Service",
    tags: ["courage", "fire", "firefighter", "service", "resilience", "bravery"],
    src: "/profile-wallpapers/Courage.jpg",
  },
  {
    key: "discovery",
    name: "Discovery",
    desc: "Life sciences discovery",
    category: "Science",
    tags: ["discovery", "science", "life sciences", "research", "innovation", "curiosity"],
    src: "/profile-wallpapers/Discovery.jpg", },
  { key: "guidance", name: "Guidance", desc: "Lighthouse guiding through uncertainty", category: "Guidance", tags: ["guidance", "lighthouse", "coaching", "mentor", "direction", "clarity"], src: "/profile-wallpapers/Guidance.jpg", },
  {
    key: "harmony",
    name: "Harmony",
    desc: "Music-inspired atmosphere",
    category: "Creative",
    tags: ["harmony", "music", "creative", "artist", "sound", "balance"],
    src: "/profile-wallpapers/Harmony.jpg",
  },
  {
    key: "inspiration",
    name: "Inspiration",
    desc: "Points of light connecting",
    category: "Inspiration",
    tags: ["inspiration", "light", "ideas", "connection", "spark", "vision"],
    src: "/profile-wallpapers/Inspiration.jpg",
  },
  {
    key: "protection",
    name: "Protection",
    desc: "Law enforcement protection and service",
    category: "Public Service",
    tags: ["protection", "law enforcement", "security", "service", "public safety", "duty"],
    src: "/profile-wallpapers/Protection.jpg",
  },
  {
    key: "rescue",
    name: "Rescue",
    desc: "Emergency response and rescue",
    category: "Public Service",
    tags: ["rescue", "emergency", "ems", "response", "service", "public safety"],
    src: "/profile-wallpapers/Rescue.jpg",
  },
];
