// lib/profileWallpapers.js

export const profileWallpapers = [
  {
    key: "building_teams",
    name: "Building Teams",
    desc: "People standing together",
    category: "Leadership",
    tags: ["teamwork", "teams", "people", "collaboration", "leadership", "community"],
    src: "/profile-wallpapers/Building_Teams.jpg",
  },
  {
    key: "forge",
    name: "Forge",
    desc: "Smoke and lava",
    category: "Forge",
    tags: ["forge", "smoke", "lava", "fire", "builder", "founder", "resilience"],
    src: "/profile-wallpapers/Forge.jpg",
  },
  {
    key: "future",
    name: "Future",
    desc: "AI shaking human hand",
    category: "Technology",
    tags: ["future", "ai", "technology", "human", "handshake", "innovation"],
    src: "/profile-wallpapers/Future.jpg",
  },
  {
    key: "growth",
    name: "Growth",
    desc: "Green forest",
    category: "Growth",
    tags: ["growth", "forest", "nature", "career growth", "development", "renewal"],
    src: "/profile-wallpapers/Growth.jpg",
  },
  {
    key: "journey",
    name: "Journey",
    desc: "Road and green fields",
    category: "Journey",
    tags: ["journey", "road", "path", "career path", "transition", "next step"],
    src: "/profile-wallpapers/Journey.jpg",
  },
  {
    key: "leadership",
    name: "Leadership",
    desc: "Sunrise in mountains",
    category: "Leadership",
    tags: ["leadership", "purpose", "sunrise", "mountains", "mission", "vision"],
    src: "/profile-wallpapers/Leadership.jpg",
  },
  {
    key: "network",
    name: "Network",
    desc: "Blue stars connecting",
    category: "Network",
    tags: ["network", "connections", "stars", "community", "relationships", "professional network"],
    src: "/profile-wallpapers/Network.jpg",
  },
  {
    key: "creation",
    name: "Creation",
    desc: "Canvas with paint pallet and brushes",
    category: "Creative",
    tags: ["creative", "creation", "art", "canvas", "design", "maker"],
    src: "/profile-wallpapers/Creation.jpg",
  },
  {
    key: "courage",
    name: "Courage",
    desc: "Fire service dedication",
    category: "Public Service",
    tags: ["courage", "fire", "firefighter", "service", "resilience", "bravery"],
    src: "/profile-wallpapers/Courage.png",
  },
  {
    key: "discovery",
    name: "Discovery",
    desc: "Life sciences discovery",
    category: "Science",
    tags: ["discovery", "science", "life sciences", "research", "innovation", "curiosity"],
    src: "/profile-wallpapers/Discovery.png",
  },
  {
    key: "guidance",
    name: "Guidance",
    desc: "Lighthouse guiding through uncertainty",
    category: "Guidance",
    tags: ["guidance", "lighthouse", "coaching", "mentor", "direction", "clarity"],
    src: "/profile-wallpapers/Guidance.png",
  },
  {
    key: "harmony",
    name: "Harmony",
    desc: "Music-inspired atmosphere",
    category: "Creative",
    tags: ["harmony", "music", "creative", "artist", "sound", "balance"],
    src: "/profile-wallpapers/Harmony.png",
  },
  {
    key: "inspiration",
    name: "Inspiration",
    desc: "Points of light connecting",
    category: "Inspiration",
    tags: ["inspiration", "light", "ideas", "connection", "spark", "vision"],
    src: "/profile-wallpapers/Inspiration.png",
  },
  {
    key: "protection",
    name: "Protection",
    desc: "Law enforcement protection and service",
    category: "Public Service",
    tags: ["protection", "law enforcement", "security", "service", "public safety", "duty"],
    src: "/profile-wallpapers/Protection.png",
  },
  {
    key: "rescue",
    name: "Rescue",
    desc: "Emergency response and rescue",
    category: "Public Service",
    tags: ["rescue", "emergency", "ems", "response", "service", "public safety"],
    src: "/profile-wallpapers/Rescue.png",
  },
];
