export const profileBanners = [
  {
    key: "build_teams",
    name: "Build Teams",
    desc: "People standing together",
    category: "Leadership",
    tags: ["teamwork", "teams", "people", "collaboration", "leadership", "community"],
    src: "/profile-banners/Build_Teams.png",
  },
  {
    key: "forge_future",
    name: "Forge the Future",
    desc: "Smoke and lava",
    category: "Forge",
    tags: ["forge", "future", "smoke", "lava", "fire", "builder", "founder", "vision"],
    src: "/profile-banners/Forge_Future.png",
  },
  {
    key: "future",
    name: "Future",
    desc: "AI shaking human hand",
    category: "Technology",
    tags: ["future", "ai", "technology", "human", "handshake", "innovation"],
    src: "/profile-banners/Future.png",
  },
  {
    key: "grow_beyond",
    name: "Grow Beyond",
    desc: "Green forest",
    category: "Growth",
    tags: ["growth", "forest", "nature", "career growth", "development", "renewal"],
    src: "/profile-banners/Grow_Beyond.png",
  },
  {
    key: "illuminate_network",
    name: "Illuminate Network",
    desc: "Blue stars connecting",
    category: "Network",
    tags: ["network", "connections", "stars", "community", "relationships", "professional network"],
    src: "/profile-banners/Illuminate_Network.png",
  },
  {
    key: "journey_continues",
    name: "The Journey Continues",
    desc: "Road and green fields",
    category: "Journey",
    tags: ["journey", "road", "path", "career path", "transition", "next step"],
    src: "/profile-banners/Journey_Continues.png",
  },
  {
    key: "lead_purpose",
    name: "Lead with Purpose",
    desc: "Sunrise in mountains",
    category: "Leadership",
    tags: ["leadership", "purpose", "sunrise", "mountains", "mission", "vision"],
    src: "/profile-banners/Lead_Purpose.png",
  },
  {
    key: "creation",
    name: "Creation",
    desc: "Canvas with painted brush strokes",
    category: "Creative",
    tags: ["creative", "creation", "art", "canvas", "design", "maker"],
    src: "/profile-banners/Creation.jpg",
  },
  {
    key: "courage",
    name: "Courage",
    desc: "Fire service dedication",
    category: "Public Service",
    tags: ["courage", "fire", "firefighter", "service", "resilience", "bravery"],
    src: "/profile-banners/Courage.jpg",
  },
  {
    key: "discovery",
    name: "Discovery",
    desc: "Life sciences discovery",
    category: "Science",
    tags: ["discovery", "science", "life sciences", "research", "innovation", "curiosity"],
    src: "/profile-banners/Discovery.jpg",
  },
  {
    key: "guidance",
    name: "Guidance",
    desc: "Lighthouse guiding through uncertainty",
    category: "Guidance",
    tags: ["guidance", "lighthouse", "coaching", "mentor", "direction", "clarity"],
    src: "/profile-banners/Guidance.jpg",
  },
  {
    key: "harmony",
    name: "Harmony",
    desc: "Music-inspired atmosphere",
    category: "Creative",
    tags: ["harmony", "music", "creative", "artist", "sound", "balance"],
    src: "/profile-banners/Harmony.jpg",
  },
  {
    key: "inspiration",
    name: "Inspiration",
    desc: "Points of light connecting",
    category: "Inspiration",
    tags: ["inspiration", "light", "ideas", "connection", "spark", "vision"],
    src: "/profile-banners/Inspiration.jpg",
  },
  {
    key: "protection",
    name: "Protection",
    desc: "Law enforcement protection and service",
    category: "Public Service",
    tags: ["protection", "law enforcement", "security", "service", "public safety", "duty"],
    src: "/profile-banners/Protection.jpg",
  },
  {
    key: "rescue",
    name: "Rescue",
    desc: "Emergency response and rescue",
    category: "Public Service",
    tags: ["rescue", "emergency", "ems", "response", "service", "public safety"],
    src: "/profile-banners/Rescue.jpg",
  },
];
