const skillsList = [
  "Communication",
  "Leadership",
  "Project Management",
  "JavaScript",
  "React",
  "Node.js",
  "Customer Service",
  "Problem Solving",
  "Teamwork",
  "Time Management",
  "Agile",
  "SQL",
  "Python",
  "Data Analysis",
  "Microsoft Office",
  "Sales",
  "Marketing",
  "Cloud Computing",
  "AWS",
  "Docker",
  "Git",
  "CSS",
  "HTML",
  "Negotiation",
  "Creativity",
  "Critical Thinking",
  "Conflict Resolution",
  "Public Speaking",
  "Attention to Detail",
  "Collaboration",
  "Adaptability",
  "Google Analytics",
  "Digital Marketing",
  "Content Management",
  "Scrum",
  "SEO",
  "Customer Retention",
  "Budgeting",
  "Team Leadership",
  "Quality Assurance",
  "UX/UI Design",
  "Networking",
  "Database Management"
];

export default skillsList;
